# Tasks dealing with rebooting the server

- name: Restart the server
  command: shutdown -r now "Ansible server reboot"
  async: 0
  poll: 0
  ignore_errors: true
  become: yes
  become_method: sudo

- name: Wait for server to come back up
  local_action: wait_for host={{ inventory_hostname }} state=started
